/**
 * NeuroScreen AI - Preset Research Benchmark Samples
 * Standardized research sample profiles for testing, validation, and benchmarking.
 */

import { PresetResearchSample } from '../types';

export const PRESET_RESEARCH_SAMPLES: PresetResearchSample[] = [
  {
    id: 'normative-control-01',
    label: 'Normative Control (Healthy Baseline)',
    category: 'normative',
    description: 'Bilateral symmetric facial kinematics, smooth voluntary arm trajectory, clear vocal resonance.',
    subjectProfile: 'Reference Control Cohort · Normal Neurological Status',
    syntheticVector: {
      facial_asymmetry_index: 3.4,
      mouth_corner_asymmetry: 0.038,
      eye_region_asymmetry: 0.032,
      eyebrow_movement_symmetry: 0.95,
      lip_mobility_symmetry: 0.96,
      temporal_facial_consistency: 0.032,
      facial_motion_range: 16.2,

      dominant_motion_frequency: 1.1,
      oscillation_amplitude: 1.6,
      movement_smoothness_sparc: -1.35,
      motion_variability: 0.09,
      peak_velocity: 1.05,
      spectral_energy_ratio: 0.04,

      mean_f0_hz: 158.4,
      pitch_variability_st: 2.6,
      jitter_percent: 0.42,
      shimmer_percent: 1.85,
      zero_crossing_rate: 0.071,
      spectral_centroid_hz: 1820,
      spectral_flux: 0.16,
      energy_rms: 0.072,
    },
    facial: {
      facialAsymmetryIndex: 3.4,
      mouthCornerAsymmetry: 0.038,
      eyeRegionAsymmetry: 0.032,
      eyebrowMovementSymmetry: 0.95,
      lipMobilitySymmetry: 0.96,
      temporalFacialConsistency: 0.032,
      maxFacialDisplacement: 16.2,
    },
    motor: {
      dominantMotionFrequencyHz: 1.1,
      oscillationAmplitude: 1.6,
      movementSmoothnessSparc: -1.35,
      motionVariability: 0.09,
      peakVelocity: 1.05,
      spectralEnergyRatio: 0.04,
      temporalConsistency: 0.94,
    },
    audio: {
      meanF0Hz: 158.4,
      pitchVariabilitySemitones: 2.6,
      jitterPercent: 0.42,
      shimmerPercent: 1.85,
      zeroCrossingRate: 0.071,
      spectralCentroidHz: 1820,
      spectralFlux: 0.16,
      energyRms: 0.072,
      speechDurationSec: 4.2,
      phonationRatio: 0.82,
    },
  },
  {
    id: 'facial-asymmetry-02',
    label: 'Hemifacial Asymmetry Profile',
    category: 'facial_asymmetry',
    description: 'Elevated oral commissure and palpebral asymmetry, unilateral smile lag, normative motor/speech.',
    subjectProfile: 'Research Sample · Unilateral Facial Asymmetry Pattern',
    syntheticVector: {
      facial_asymmetry_index: 12.8,
      mouth_corner_asymmetry: 0.165,
      eye_region_asymmetry: 0.112,
      eyebrow_movement_symmetry: 0.72,
      lip_mobility_symmetry: 0.68,
      temporal_facial_consistency: 0.125,
      facial_motion_range: 11.2,

      dominant_motion_frequency: 1.3,
      oscillation_amplitude: 1.9,
      movement_smoothness_sparc: -1.52,
      motion_variability: 0.11,
      peak_velocity: 0.98,
      spectral_energy_ratio: 0.06,

      mean_f0_hz: 162.1,
      pitch_variability_st: 2.2,
      jitter_percent: 0.68,
      shimmer_percent: 2.45,
      zero_crossing_rate: 0.078,
      spectral_centroid_hz: 1790,
      spectral_flux: 0.14,
      energy_rms: 0.066,
    },
    facial: {
      facialAsymmetryIndex: 12.8,
      mouthCornerAsymmetry: 0.165,
      eyeRegionAsymmetry: 0.112,
      eyebrowMovementSymmetry: 0.72,
      lipMobilitySymmetry: 0.68,
      temporalFacialConsistency: 0.125,
      maxFacialDisplacement: 11.2,
    },
    motor: {
      dominantMotionFrequencyHz: 1.3,
      oscillationAmplitude: 1.9,
      movementSmoothnessSparc: -1.52,
      motionVariability: 0.11,
      peakVelocity: 0.98,
      spectralEnergyRatio: 0.06,
      temporalConsistency: 0.89,
    },
    audio: {
      meanF0Hz: 162.1,
      pitchVariabilitySemitones: 2.2,
      jitterPercent: 0.68,
      shimmerPercent: 2.45,
      zeroCrossingRate: 0.078,
      spectralCentroidHz: 1790,
      spectralFlux: 0.14,
      energyRms: 0.066,
      speechDurationSec: 4.1,
      phonationRatio: 0.76,
    },
  },
  {
    id: 'kinetic-tremor-03',
    label: 'Kinetic Tremor & Motor Instability Profile',
    category: 'kinetic_instability',
    description: 'Prominent 5.2 Hz rhythmic arm oscillation, fragmented SPARC trajectory, mild vocal tremor.',
    subjectProfile: 'Research Sample · Upper-Limb Kinetic Instability Pattern',
    syntheticVector: {
      facial_asymmetry_index: 4.9,
      mouth_corner_asymmetry: 0.052,
      eye_region_asymmetry: 0.046,
      eyebrow_movement_symmetry: 0.89,
      lip_mobility_symmetry: 0.91,
      temporal_facial_consistency: 0.048,
      facial_motion_range: 13.5,

      dominant_motion_frequency: 5.2,
      oscillation_amplitude: 6.8,
      movement_smoothness_sparc: -2.85,
      motion_variability: 0.28,
      peak_velocity: 0.62,
      spectral_energy_ratio: 0.38,

      mean_f0_hz: 148.5,
      pitch_variability_st: 1.8,
      jitter_percent: 0.98,
      shimmer_percent: 3.42,
      zero_crossing_rate: 0.088,
      spectral_centroid_hz: 1910,
      spectral_flux: 0.11,
      energy_rms: 0.052,
    },
    facial: {
      facialAsymmetryIndex: 4.9,
      mouthCornerAsymmetry: 0.052,
      eyeRegionAsymmetry: 0.046,
      eyebrowMovementSymmetry: 0.89,
      lipMobilitySymmetry: 0.91,
      temporalFacialConsistency: 0.048,
      maxFacialDisplacement: 13.5,
    },
    motor: {
      dominantMotionFrequencyHz: 5.2,
      oscillationAmplitude: 6.8,
      movementSmoothnessSparc: -2.85,
      motionVariability: 0.28,
      peakVelocity: 0.62,
      spectralEnergyRatio: 0.38,
      temporalConsistency: 0.71,
    },
    audio: {
      meanF0Hz: 148.5,
      pitchVariabilitySemitones: 1.8,
      jitterPercent: 0.98,
      shimmerPercent: 3.42,
      zeroCrossingRate: 0.088,
      spectralCentroidHz: 1910,
      spectralFlux: 0.11,
      energyRms: 0.052,
      speechDurationSec: 4.5,
      phonationRatio: 0.73,
    },
  },
  {
    id: 'dysphonia-dysprosody-04',
    label: 'Dysphonic & Hypokinetic Speech Profile',
    category: 'vocal_dysphonia',
    description: 'Elevated acoustic jitter & shimmer, reduced pitch variability (monotone), hypophonia.',
    subjectProfile: 'Research Sample · Acoustic Vocal Instability & Monopitch',
    syntheticVector: {
      facial_asymmetry_index: 5.8,
      mouth_corner_asymmetry: 0.061,
      eye_region_asymmetry: 0.054,
      eyebrow_movement_symmetry: 0.88,
      lip_mobility_symmetry: 0.86,
      temporal_facial_consistency: 0.059,
      facial_motion_range: 9.8,

      dominant_motion_frequency: 2.1,
      oscillation_amplitude: 2.8,
      movement_smoothness_sparc: -1.78,
      motion_variability: 0.14,
      peak_velocity: 0.74,
      spectral_energy_ratio: 0.11,

      mean_f0_hz: 132.0,
      pitch_variability_st: 0.95,
      jitter_percent: 1.64,
      shimmer_percent: 5.12,
      zero_crossing_rate: 0.115,
      spectral_centroid_hz: 2480,
      spectral_flux: 0.075,
      energy_rms: 0.034,
    },
    facial: {
      facialAsymmetryIndex: 5.8,
      mouthCornerAsymmetry: 0.061,
      eyeRegionAsymmetry: 0.054,
      eyebrowMovementSymmetry: 0.88,
      lipMobilitySymmetry: 0.86,
      temporalFacialConsistency: 0.059,
      maxFacialDisplacement: 9.8,
    },
    motor: {
      dominantMotionFrequencyHz: 2.1,
      oscillationAmplitude: 2.8,
      movementSmoothnessSparc: -1.78,
      motionVariability: 0.14,
      peakVelocity: 0.74,
      spectralEnergyRatio: 0.11,
      temporalConsistency: 0.84,
    },
    audio: {
      meanF0Hz: 132.0,
      pitchVariabilitySemitones: 0.95,
      jitterPercent: 1.64,
      shimmerPercent: 5.12,
      zeroCrossingRate: 0.115,
      spectralCentroidHz: 2480,
      spectralFlux: 0.075,
      energyRms: 0.034,
      speechDurationSec: 4.8,
      phonationRatio: 0.69,
    },
  },
];
